// Auto-generated component from Figma design
// Figma Component: Primary Button
// Figma ID: figma-1
// Generated by GoldenEye Component Generator

import React from 'react';
import './PrimaryButton.css';

interface PrimaryButtonProps {
  text?: string;
  onClick?: () => void;
  disabled?: boolean;
  variant?: 'primary' | 'secondary' | 'outline';
  size?: 'small' | 'medium' | 'large';
  className?: string;
  id?: string;
}

export const PrimaryButton: React.FC<PrimaryButtonProps> = ({
  text,
  onClick,
  disabled,
  variant,
  size,
  className,
  id,
  ...props
}) => {
  return (
    <div 
      className={`primarybutton ${props.className || ''}`}
      id={props.id}
      {...props}
    >
      <button onClick={props.onClick} disabled={props.disabled}>
        {props.text || 'PrimaryButton'}
      </button>
    </div>
  );
};
