// Auto-generated component from Figma design
// Figma Component: User Card
// Figma ID: figma-2
// Generated by GoldenEye Component Generator

import React from 'react';
import './UserCard.css';

interface UserCardProps {
  title?: string;
  content?: React.ReactNode;
  onClick?: () => void;
  className?: string;
  id?: string;
}

export const UserCard: React.FC<UserCardProps> = ({
  title,
  content,
  onClick,
  className,
  id,
  ...props
}) => {
  return (
    <div 
      className={`usercard ${props.className || ''}`}
      id={props.id}
      {...props}
    >
      <div className="card-header">
        <h3>{props.title || 'UserCard'}</h3>
      </div>
      <div className="card-content">
        {props.content || 'Card content goes here'}
      </div>
    </div>
  );
};
