// Auto-generated component from Figma design
// Figma Component: Search Input
// Figma ID: figma-3
// Generated by GoldenEye Component Generator

import React from 'react';
import './SearchInput.css';

interface SearchInputProps {
  placeholder?: string;
  value?: string;
  onChange?: (value: string) => void;
  type?: 'text' | 'email' | 'password' | 'number';
  className?: string;
  id?: string;
}

export const SearchInput: React.FC<SearchInputProps> = ({
  placeholder,
  value,
  onChange,
  type,
  className,
  id,
  ...props
}) => {
  return (
    <div 
      className={`searchinput ${props.className || ''}`}
      id={props.id}
      {...props}
    >
      <input 
        type={props.type || 'text'}
        placeholder={props.placeholder}
        value={props.value}
        onChange={(e) => props.onChange?.(e.target.value)}
      />
    </div>
  );
};
